data_kendaraan = ["B 6118 PZZ", "pcx", "125cc", "hitam"]
data_kendaraan.append("Rp.20,000,000")
data_kendaraan.append(2)
data_kendaraan.insert(2, "honda")
data_kendaraan.insert(3, "motor")
print(data_kendaraan)
print("kode kendaraan  :",data_kendaraan[0])
print("nama kendaraan  :",data_kendaraan[1])
print("merk kendaraan  :",data_kendaraan[2])
print("jenis kendaraan :",data_kendaraan[3])
print("cc kendaraan    :",data_kendaraan[4])
print("warna kendaraan :",data_kendaraan[5])
print("harga           :",data_kendaraan[6])
print("jumlah ban      :",data_kendaraan[7])
